function writeSWATdotFIG(configurationData,outputFilename, verbose)
%%
masterTimer = tic;

if (nargin<3 || isempty(verbose))
    verbose = false;
end

validateattributes(verbose,{'logical'},{'scalar'});
%%
if (verbose)
    fprintf('Writing the configuration to %s. This may take some time. Please wait.\n',outputFilename);
end

%%
if (verbose)
    wbHandle = waitbar(0,'Reading the configuration file. Please wait.\n');
end
%%
fid = fopen(outputFilename,'w');
if (fid == -1)
    error('could not open %s for writing.',outputFilename);
end

%%
nCommands = size(configurationData,1);
for idx = 1:nCommands
    try
        if (verbose)
            waitbar(idx/nCommands, wbHandle);
        end
        
        % Getting Command Code
        command = configurationData.commandCode(idx);
        CMDDetail = configurationData.commandDetail{idx};
        switch command
            case 0 % finish command
                fprintf(fid,'%-10s%6d\n','finish',0);
            case 1 % subbasin command
                if (isnan(CMDDetail.GIS_CODE))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%27s%s%d\n', ...
                            'subbasin', ...
                            1, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.SUB_NUM, ...
                            '', ...
                            '   Subbasin: ', ...
                            CMDDetail.SUB_NUM);
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%18s%9d\n', ...
                            'subbasin', ...
                            1, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.SUB_NUM, ...
                            '', ...
                            CMDDetail.GIS_CODE);
                end
                 fprintf(fid,'%23s\n',CMDDetail.SUBFILE);
            case 2 % route command
                if (isfield(CMDDetail,'FLOW_OVN'))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%6d%7s%6.3f\n', ...
                            'route', ...
                            2, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.RCH_NUM, ...
                            CMDDetail.HYD_NUM, ...
                            '', ...
                            CMDDetail.FLOW_OVN);
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%6d\n', ...
                            'route', ...
                            2, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.RCH_NUM, ...
                            CMDDetail.HYD_NUM);
                end
                    
                fprintf(fid,'%23s%13s\n',CMDDetail.RTEFILE,CMDDetail.SWQFILE);
            case 3 % routres command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d\n', ...
                        'routres', ...
                        3, ...
                        CMDDetail.HYD_STOR, ...
                        CMDDetail.RES_NUM, ...
                        CMDDetail.HYD_NUM);
                fprintf(fid,'%23s%13s\n',CMDDetail.RESFILE,CMDDetail.LWQFILE);
            case 4 % transfer command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d%6d%6.3f%9d%3d\n', ...
                        'transfer', ...
                        4, ...
                        CMDDetail.DEP_TYPE, ...
                        CMDDetail.DEP_NUM, ...
                        CMDDetail.DEST_TYPE, ...
                        CMDDetail.DEST_NUM, ...
                        CMDDetail.TRANS_AMT, ...
                        CMDDetail.TRANS_CODE, ...
                        CMDDetail.TRANS_SE);
                fprintf(fid, ...
                        '%14d%4d%4d\n', ...
                        CMDDetail.MO_TRANSB, ...
                        CMDDetail.MO_TRANSE, ...
                        CMDDetail.IH_TRANS);
            case 5 %add command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d\n', ...
                        'add', ...
                        5, ...
                        CMDDetail.HYD_STOR, ...
                        CMDDetail.HYD_NUM1, ...
                        CMDDetail.HYD_NUM2);
            case 6 % rechour command
                if (isfield(CMDDetail,'DRAINAGE_AREA'))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%13s%6.3f\n', ...
                            'rechour', ...
                            6, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEHR_NUM, ...
                            ' ', ...
                            CMDDetail.DRAINAGE_AREA);                            
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d\n', ...
                            'rechour', ...
                            6, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEHR_NUM);
                end
                fprintf(fid,'%-10s%13s\n','Pnt.Source',CMDDetail.FILE_HR);
            case 7 % recmon command
                if (isfield(CMDDetail,'DRAINAGE_AREA'))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%13s%6.3f\n', ...
                            'recmon', ...
                            7, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEMON_NUM, ...
                            ' ', ...
                            CMDDetail.DRAINAGE_AREA);                            
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d\n', ...
                            'recmon', ...
                            7, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEMON_NUM);
                end
                fprintf(fid,'%-10s%13s\n','Pnt.Source',CMDDetail.FILE_MON);
            case 8 % recyear command
                if (isfield(CMDDetail,'DRAINAGE_AREA'))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%13s%6.3f\n', ...
                            'recyear', ...
                            8, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEYR_NUM, ...
                            ' ', ...
                            CMDDetail.DRAINAGE_AREA);                            
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d\n', ...
                            'recyear', ...
                            8, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEYR_NUM);
                end
                fprintf(fid,'%-10s%13s\n','Pnt.Source',CMDDetail.FILE_YR);
            case 9 % save command
                fprtinf(fid, ...
                        '%-10s%6d%6d%6d%6d%6d\n', ...
                        'save', ...
                        9, ...
                        CMDDetail.HYD_NUM, ...
                        CMDDetail.FILESAVE_NUM, ...
                        CMDDetail.PRINT_FREQ, ...
                        CMDDetail.PRINT_FMT);
                fprintf(fid,'%23s\n',CMDDetail.FILE_MASS);
             case 10 % recday command
                if (isfield(CMDDetail,'DRAINAGE_AREA'))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%13s%6.3f\n', ...
                            'recday', ...
                            10, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEDAY_NUM, ...
                            ' ', ...
                            CMDDetail.DRAINAGE_AREA);                            
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d\n', ...
                            'recday', ...
                            10, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILEDAY_NUM);
                end
                fprintf(fid,'%-10s%13s\n','Pnt.Source',CMDDetail.FILE_DAY);
            case 11 % reccnst command
                if (isfield(CMDDetail,'DRAINAGE_AREA'))
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d%13s%6.3f\n', ...
                            'reccnst', ...
                            11, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILECNST_NUM, ...
                            ' ', ...
                            CMDDetail.DRAINAGE_AREA);                            
                else
                    fprintf(fid, ...
                            '%-10s%6d%6d%6d\n', ...
                            'reccnst', ...
                            11, ...
                            CMDDetail.HYD_STOR, ...
                            CMDDetail.FILECNST_NUM);
                end
                fprintf(fid,'%-10s%13s\n','Pnt.Source',CMDDetail.FILE_CNST);
            case 12 % structure command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%13s%6.3f\n', ...
                        'structure', ...
                        12, ...
                        CMDDetail.HYD_STOR, ...
                        CMDDetail.HYD_NUM, ...
                        ' ', ...
                        CMDDetail.AERATION_COEF);
            case 13 % apex command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d\n', ...
                        'apex', ...
                        13 ,...
                        CMDDetail.HYD_STOR, ...
                        CMDDetail.FILECONC_NUM);
                fprintf(fid,'%23s\n',CMDDetail.APEX_IN);
            case 14 % saveconc command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d\n', ...
                        'saveconc', ...
                        14, ...
                        CMDDetail.HYD_NUM, ...
                        CMDDetail.FILECONC_NUM, ...
                        CMDDetail.PRINT_FREQ);
                fprintf(fid,'%23s\n',CMDDetail.FILE_CONC);
            case 16 % autocal command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d\n', ...
                        'aitocal', ...
                        16, ...
                        CMDDetail.HYD_NUM, ...
                        CMDDetail.FILECAL_NUM, ...
                        CMDDetail.PRINT_FREQ);
                fprintf(fid,'%23s\n',CMDDetail.FILE_ACAL);
            case 17 % route unit command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d\n', ...
                        'routeunit', ...
                        17, ...
                        CMDDetail.HYD_STOR, ...
                        CMDDetail.RU_NUM, ...
                        CMDDetail.SUB_NUM);
                fprintf(fid,'%23s\n',CMDDetail.RU_FILE);
            case 18 % route landscape command
                fprintf(fid, ...
                        '%-10s%6d%6d%6d%6d%6d%6d%6d%6d%6d\n', ...
                        'routlscape', ...
                        18, ...
                        CMDDetail.HYD_STOR, ...
                        CMDDetail.LU_NUM, ...
                        CMDDetail.HYD_NUM, ...
                        CMDDetail.SUB_NUM, ...
                        CMDDetail.SURQ_RCO, ...
                        CMDDetail.LATQ_RCO, ...
                        CMDDetail.GWQ_RCO, ...
                        CMDDetail.TILEQ_RCO);
            otherwise
%                 error('command code: %d is not recognies.',command);
        end
    catch ME
        fclose(fid);
        if (verbose)
            close(wbHandle);
        end
        rethrow(ME);
    end
end

fclose(fid);
if (verbose)
    close(wbHandle);
    fprintf('Finished in %0.2f [s].\n',toc(masterTimer));
end


