function recdayData = readSWATRecDay(filename) 
%% opening file
fid = fopen(filename,'r');
if (fid==-1)
    error('Could not open %s for reading.',filename);
end

%%
recdayData.titleLines = cell(5,1);

%% Reading the RECDAY file
try
    % Reading the title lines.
    for idx = 1:5
        recdayData.titleLines{idx} = fgetl(fid);
    end
    fgetl(fid); % skipping the variable names
catch ME
    % making sure the file is closed in case of error.
    fclose(fid);
    rethrow(ME);
end
fclose(fid);

%% Reading the data
recdayData.data = readtable(filename, ...
                        'FileType', 'text', ...
                        'ReadVariableNames', false, ...
                        'HeaderLines', 6);
% Setting the column names
recdayData.data.Properties.VariableNames={ ...
    'DAY', 'YEAR', ...
    'FLODAY', ...
    'SEDDAY', ...
    'ORGNDAY', ...
    'ORGPDAY', ...
    'NO3DAY', ...
    'NH3DAY', ...
    'NO2DAY', ...
    'MINPDAY', ...
    'CBODDAY', ...
    'DISOXDAY', ...
    'CHLADAY', ...
    'SOLPSTDAY', ...
    'SRBPSTDAY', ...
    'BACTPDAY', ...
    'BACTLPDAY', ...
    'CMTL1DAY', ...
    'CMTL2DAY', ...
    'CMTL3DAY'};

end

                    