function reccnstData = readSWATRecCnst(filename)
%% 
variableNames = {
    'FLOCNST', ...
    'SEDCNST', ...
    'ORGNCNST', ...
    'ORGPCNST', ...
    'NO3CNST', ...
    'NH3CNST', ...
    'NO2CNST', ...
    'MINPCNST', ...
    'CBODCNST', ...
    'DISOXCNST', ...
    'CHLACNST', ...
    'SOLPSTCNST', ...
    'SRBPSTCNST', ...
    'BACTPSTCNST', ...
    'BATCLPCNST', ...
    'CMTL1CNST', ...
    'CMTL2CNST', ...
    'CMTL3CNST'};
    
%% opening file
fid = fopen(filename,'r');
if (fid==-1)
    error('Could not open %s for reading.',filename);
end

%%
reccnstData.titleLines = cell(5,1);

%% Reading the RECDAY file
try
    % Reading the title lines.
    for idx = 1:5
        reccnstData.titleLines{idx} = fgetl(fid);
    end
    fgetl(fid); % skipping the variable names
    
    % Getting the data line
    tmpData = str2num(fgetl(fid));
    for idx = 1:numel(variableNames)
        reccnstData.(variableNames{idx})=tmpData(idx);
    end
catch ME
    % making sure the file is closed in case of error.
    fclose(fid);
    rethrow(ME);
end
fclose(fid);

end
