function writeSWATRecDay(outFilename,recdayData)
%%
variableNames ={'DAY', 4; ...
                'YEAR', 5; ...
                'FLODAY', 17; ...
                'SEDDAY', 17; ...
                'ORGNDAY', 17; ...
                'ORGPDAY', 17; ...
                'NO3DAY', 17; ...
                'NH3DAY', 17; ...
                'NO2DAY', 17; ...
                'MINPDAY', 17; ...
                'CBODDAY', 17; ...
                'DISOXDAY', 17; ...
                'CHLADAY', 17; ...
                'SOLPSTDAY', 17; ...
                'SRBPSTDAY', 17; ...
                'BACTPDAY', 17; ...
                'BACTLPDAY', 17; ...
                'CMTL1DAY', 17; ...
                'CMTL2DAY', 17; ...
                'CMTL3DAY',  17};

%% opening file
fid = fopen(outFilename,'w');
if (fid==-1)
    error('Could not open %s for writing.',filename);
end

%% writing the RECDAY file
try
    % writing the title lines.
    for idx = 1:5
        fprintf(fid,'%s\n',recdayData.titleLines{idx});
    end
    % writing the variable names
    for idx = 1:size(variableNames,1)
        formatStr = sprintf('%%%ds',variableNames{idx,2});
        fprintf(fid,formatStr,variableNames{idx,1});
    end
    fprintf(fid,'\n');
    
    % writing the data
    formatStr = '%4d%5d%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E%17.10E\n';
    fprintf(fid,formatStr,table2array(recdayData.data)');
catch ME
    % making sure the file is closed in case of error.
    fclose(fid);
    rethrow(ME);
end
fclose(fid);

end
