function reccnstData = writeSWATRecCnst(outFilename,reccnstData)
%% 
variableNames = {
    'FLOCNST', ...
    'SEDCNST', ...
    'ORGNCNST', ...
    'ORGPCNST', ...
    'NO3CNST', ...
    'NH3CNST', ...
    'NO2CNST', ...
    'MINPCNST', ...
    'CBODCNST', ...
    'DISOXCNST', ...
    'CHLACNST', ...
    'SOLPSTCNST', ...
    'SRBPSTCNST', ...
    'BACTPSTCNST', ...
    'BATCLPCNST', ...
    'CMTL1CNST', ...
    'CMTL2CNST', ...
    'CMTL3CNST'};
    
%% opening file
fid = fopen(outFilename,'w');
if (fid==-1)
    error('Could not open %s for writing.',outFilename);
end

%% Reading the RECDAY file
try
    % writing the title lines.
    for idx = 1:5
        fprintf(fid,'%s\n',reccnstData.titleLines{idx});
    end
    % writing the variable names
    fprintf(fid,'%10s',' ');
    for idx = 1:numel(variableNames)
        fprintf(fid,'%17s',variableNames{idx});
    end
    fprintf(fid,'\n');
    
    % writing the data line
    fprintf(fid,'%10s',' ');
    for idx = 1:numel(variableNames)
        fprintf(fid,'%17.10E',reccnstData.(variableNames{idx}));
    end
    fprintf(fid,'\n');
catch ME
    % making sure the file is closed in case of error.
    fclose(fid);
    rethrow(ME);
end
fclose(fid);

end
